//main layout
//layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import PageHeader from "@/components/PageHeader";
import PageFooter from "@/components/PageFooter";
import GoogleAnalyticsOptOutScript from "@/components/GoogleAnalyticsOptOutScript";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background min-h-screen flex flex-col font-sans">
        <GoogleAnalyticsOptOutScript />
        <PageHeader />
        <main className="flex-1 container mx-auto p-6 mt-6 w-full">
          {children}
        </main>
        <PageFooter />
      </body>
    </html>
  );
}
